//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liceu
    {
        public Liceu()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id_liceu { get; set; }
        public string nume { get; set; }
        public double rating_total { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
