//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tema
    {
        public Tema()
        {
            this.Comentarius = new HashSet<Comentariu>();
            this.Participas = new HashSet<Participa>();
            this.Ratings = new HashSet<Rating>();
            this.Submits = new HashSet<Submit>();
        }

        [Required]
        public int id_tema { get; set; }

        [Required]
        public string enunt { get; set; }

        [Required]
        public string titlu { get; set; }

        [Required]
        public int id_prof { get; set; }

        [Required]
        public int id_in_out { get; set; }

        public Nullable<int> id_help { get; set; }

        [Required]
        public System.DateTime deadline { get; set; }

        [Required]
        public int privat { get; set; }
    
        public virtual ICollection<Comentariu> Comentarius { get; set; }
        public virtual Fisier Fisier { get; set; }
        public virtual Fisier Fisier1 { get; set; }
        public virtual ICollection<Participa> Participas { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Submit> Submits { get; set; }
        public virtual User User { get; set; }
    }

}
